# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.14
    steps:
      - checkout
      - run:
          name: Install with pip
          command: |
            python -m pip install requests termcolor

      - run:
          name: Validate roles JSON file
          command: |
            python validate_roles.py

      - run:
          name: Install sphinx deps
          command: |
            python -m pip install -r requirements.txt

      - run:
          name: Build sphinx
          command: |
            sphinx-build --color -W --keep-going -b html . _build/html

      - store_artifacts:
          path: /root/project/_build/html
          destination: html
